set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR x86_64)
set(CMAKE_TRY_COMPILE_PLATFORM_VARIABLES ZIG_EXECUTABLE)

if(NOT ZIG_EXECUTABLE)
    message(FATAL_ERROR "Set ZIG_EXECUTABLE to a Zig 0.16.0 executable")
endif()

set(CMAKE_C_COMPILER "${ZIG_EXECUTABLE}")
set(CMAKE_C_COMPILER_ARG1 cc)
set(CMAKE_CXX_COMPILER "${ZIG_EXECUTABLE}")
set(CMAKE_CXX_COMPILER_ARG1 c++)
set(CMAKE_C_COMPILER_TARGET x86_64-linux-gnu.2.17)
set(CMAKE_CXX_COMPILER_TARGET x86_64-linux-gnu.2.17)
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
set(CMAKE_BUILD_WITH_INSTALL_RPATH TRUE)

# FLTK is bundled, while X11 and font rendering come from the desktop system.
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY BOTH)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE BOTH)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE BOTH)
